/*
 * Minesweeper Server
 *
 * This is a Minesweeper server.  You can find out more about it at [github.com/seguijoaquin/minesweeper](github.com/seguijoaquin/minesweeper) 
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProblemDetail struct {
	Type_ string `json:"type"`
	Title string `json:"title"`
	Status string `json:"status"`
	Detail string `json:"detail"`
	Instance string `json:"instance"`
}
