/*
 * Minesweeper Server
 *
 * This is a Minesweeper server.  You can find out more about it at [github.com/seguijoaquin/minesweeper](github.com/seguijoaquin/minesweeper) 
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GameRequest struct {
	Rows int32 `json:"rows"`
	Cols int32 `json:"cols"`
	Mines int32 `json:"mines"`
}
